import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const japanRich = localFont({
  src: "./fonts/JapanRich-Regular.woff",
  variable: "--font-japan-rich",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nihongo Quest",
  description: "Generated by create Nihongo Quest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${japanRich.variable} antialiased`}>{children}</body>
    </html>
  );
}
